### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by vardhanv** [davheld/GOTURN#74]
Hi,

I was able to build everything, but get a segmentation fault when i try to save videos. Could you help me debug this.. ?

```
vardhan@96bddd4aeea2:/workspace/GOTURN$ bash scripts/save_videos_test.sh imagedata++
Saving output to 
Setting up Caffe in GPU mode with ID: 0
Setting phase to test
Network image size: 227, 227
Found 14 videos...
Loading video: 01-Light
scripts/save_videos_test.sh: line 26:   254 Segmentation fault      (core dumped) build/save_videos_vot $VIDEOS_FOLDER $DEPLOY_PROTO $CAFFE_MODEL $OUTPUT_FOLDER $GPU_ID
vardhan@96bddd4aeea2:/workspace/GOTURN$ 
vardhan@96bddd4aeea2:/workspace/GOTURN$ bash -x scripts/save_videos_test.sh imagedata++
+ '[' -z imagedata++ ']'
+ GPU_ID=0
+ VIDEOS_FOLDER=imagedata++
+ FOLDER=GOTURN1_test
+ DEPLOY_PROTO=nets/tracker.prototxt
+ CAFFE_MODEL=nets/models/pretrained_model/tracker.caffemodel
+ OUTPUT_FOLDER=nets/tracker_output/GOTURN1_test
+ echo 'Saving output to '
Saving output to 
+ build/save_videos_vot imagedata++ nets/tracker.prototxt nets/models/pretrained_model/tracker.caffemodel nets/tracker_output/GOTURN1_test 0
Setting up Caffe in GPU mode with ID: 0
Setting phase to test
Network image size: 227, 227
Found 14 videos...
Loading video: 01-Light
scripts/save_videos_test.sh: line 26:   259 Segmentation fault      (core dumped) build/save_videos_vot $VIDEOS_FOLDER $DEPLOY_PROTO $CAFFE_MODEL $OUTPUT_FOLDER $GPU_ID
```

**Comment by yuyangyg** [comment]
Maybe,you can check your dataset whether it has groundtruth.txt

**Comment by vardhanv** [comment]
Thanks this was resolved. linking to wrong caffe libraries

**Comment by RJVisee44** [comment]
@vardhanv 
I'm pretty sure I'm linking to correct caffe libraries, but still getting this segmentation fault. How did you re-link?
